# This is a basic workflow to help you get started with Actions

name: Upload to github-pages

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      -
        name: Build svelte
        run: |
          echo Installing dependencies
          npm ci
          echo Building app
          npm run build
          echo App builded correctly

      -
        name: Upload to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2.2.0
        with:
          build_dir: public
          committer: David Castilla Ortiz <im@dcxo.dev>
          author: David Castilla Ortiz <im@dcxo.dev>
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
